backend:
  name: github
  repo: razvantimis/razvantimis.github.io
  branch: main
  base_url: https://us-central1-razvantimis-webpage.cloudfunctions.net/ # The base URL for your Firebase Function
  auth_endpoint: /oauthGithub/auth # The path to the OAuth endpoint of the function
media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    path: "{{year}}/{{month}}/{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { label: Cover, name: cover, widget: "image", required: false }
      - {
          label: Youtube url,
          name: youtubeUrl,
          widget: "string",
          required: false,
        }
      - name: category
        label: Category
        widget: relation
        collection: category
        searchFields: [name]
        valueField: name
      - name: subCategory
        label: Sub Category
        widget: relation
        collection: subCategory
        searchFields: [name]
        valueField: name
      - { label: Tags, name: tags, widget: "list", default: [] }
      - { name: body, label: Body, widget: markdown }
  - name: category
    label: Categories
    folder: content/category
    create: true
    fields:
      - { name: name, label: Name }
      - { name: slug, label: Slug }
  - name: subCategory
    label: Sub Categories
    folder: content/subCategory
    create: true
    fields:
      - { name: name, label: Name }
      - { name: slug, label: Slug }
